//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapleRoll.Properties {
    using System;



    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapleRoll.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        //internal static System.Drawing.Bitmap Flip_Icon {
        //    get {
        //        object obj = ResourceManager.GetObject("Flip_Icon", resourceCulture);
        //        return ((System.Drawing.Bitmap)(obj));
        //    }
        //}

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        //internal static System.Drawing.Bitmap Heads_Icon {
        //    get {
        //        object obj = ResourceManager.GetObject("Heads_Icon", resourceCulture);
        //        return ((System.Drawing.Bitmap)(obj));
        //    }
        //}

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        //internal static System.Drawing.Bitmap Tails_Icon {
        //    get {
        //        object obj = ResourceManager.GetObject("Tails_Icon", resourceCulture);
        //        return ((System.Drawing.Bitmap)(obj));
        //    }
        //}

        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        /// 

        internal static System.IO.UnmanagedMemoryStream wow_c_101soundboards
        {
            get
            {
                return ResourceManager.GetStream("wow_c_101soundboards", resourceCulture);
            }
        }



        internal static System.IO.UnmanagedMemoryStream oh_man_deafult
        {
            get
            {
                return ResourceManager.GetStream("oh_man_deafult", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream oh_yeah_Default
        {
            get
            {
                return ResourceManager.GetStream("oh_yeah_Default", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream roll_default
        {
            get
            {
                return ResourceManager.GetStream("roll_default", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream no_swiping_Default
        {
            get
            {
                return ResourceManager.GetStream("no_swiping_Default", resourceCulture);
            }
        }




        internal static System.IO.UnmanagedMemoryStream dissapointment
        {
            get
            {
                return ResourceManager.GetStream("dissapointment", resourceCulture);
            }
        }


        internal static System.IO.UnmanagedMemoryStream emotional_damage
        {
            get
            {
                return ResourceManager.GetStream("emotional-damage", resourceCulture);
            }
        }

        internal static System.IO.UnmanagedMemoryStream bob
        {
            get
            {
                return ResourceManager.GetStream("bob", resourceCulture);
            }
        }

        internal static System.IO.UnmanagedMemoryStream niiice
        {
            get
            {
                return ResourceManager.GetStream("niiice", resourceCulture);
            }
        }

        internal static System.IO.UnmanagedMemoryStream harry_potter_theme
        {
            get
            {
                return ResourceManager.GetStream("harry_potter_theme", resourceCulture);
            }
        }

        internal static System.IO.UnmanagedMemoryStream mario_yahoo
        {
            get
            {
                return ResourceManager.GetStream("mario_yahoo", resourceCulture);
            }
        }

        internal static System.IO.UnmanagedMemoryStream yer_a_wizard_harry
        {
            get
            {
                return ResourceManager.GetStream("yer_a_wizard_harry", resourceCulture);
            }
        }

        internal static System.IO.UnmanagedMemoryStream door_shuts
        {
            get
            {
                return ResourceManager.GetStream("door_shuts", resourceCulture);
            }
        }

        internal static System.IO.UnmanagedMemoryStream knocking_on_door
        {
            get
            {
                return ResourceManager.GetStream("knocking_on_door", resourceCulture);
            }
        }

        //Family Guy

        internal static System.IO.UnmanagedMemoryStream piece_ofcandy_familyguy
        {
            get
            {
                return ResourceManager.GetStream("piece_ofcandy_familyguy", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream ha_familyguy
        {
            get
            {
                return ResourceManager.GetStream("ha_familyguy", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream jackpot_familyguy
        {
            get
            {
                return ResourceManager.GetStream("jackpot_familyguy", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream shut_up_meg_familyguy
        {
            get
            {
                return ResourceManager.GetStream("shut_up_meg_familyguy", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream congratulations_Familyguy
        {
            get
            {
                return ResourceManager.GetStream("congratulations_Familyguy", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream almost_familyguy
        {
            get
            {
                return ResourceManager.GetStream("almost_familyguy", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream bow_chicka_wow_familyguy
        {
            get
            {
                return ResourceManager.GetStream("bow_chicka_wow_familyguy", resourceCulture);
            }
        }

        //mario

        internal static System.IO.UnmanagedMemoryStream bro_mario
        {
            get
            {
                return ResourceManager.GetStream("bro_mario", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream coin_mario
        {
            get
            {
                return ResourceManager.GetStream("coin_mario", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream its_mario_time
        {
            get
            {
                return ResourceManager.GetStream("its_mario_time", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream oh_uh_mario
        {
            get
            {
                return ResourceManager.GetStream("oh_uh_mario", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream mama_mia_mario
        {
            get
            {
                return ResourceManager.GetStream("mama_mia_mario", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream star_theme_mario
        {
            get
            {
                return ResourceManager.GetStream("star_theme_mario", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream wahhhhh_mario
        {
            get
            {
                return ResourceManager.GetStream("wahhhhh_mario", resourceCulture);
            }
        }

        //zelda

        internal static System.IO.UnmanagedMemoryStream item_Zelda
        {
            get
            {
                return ResourceManager.GetStream("item_Zelda", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream low_hp_Zelda
        { 
            get
            {
                return ResourceManager.GetStream("low_hp_Zelda", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream chest1_zelda
        {
            get
            {
                return ResourceManager.GetStream("chest1_zelda", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream link_fall_zelda
        {
            get
            {
                return ResourceManager.GetStream("link_fall_zelda", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream prayer_zelda
        {
            get
            {
                return ResourceManager.GetStream("prayer_zelda", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream link_death_zelda
        {
            get
            {
                return ResourceManager.GetStream("link_death_zelda", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream bounce_Zelda
        {
            get
            {
                return ResourceManager.GetStream("bounce_Zeldao", resourceCulture);
            }
        }

        //Bender

        internal static System.IO.UnmanagedMemoryStream yeah_bender
        {
            get
            {
                return ResourceManager.GetStream("yeah_bender", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream pass_Bender
        {
            get
            {
                return ResourceManager.GetStream("pass_Bender", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream oh_my_god_Bender
        {
            get
            {
                return ResourceManager.GetStream("oh_my_god_Bender", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream ah_crap_Bender
        {
            get
            {
                return ResourceManager.GetStream("ah_crap_Bender", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream whoa_mama_Bender
        {
            get
            {
                return ResourceManager.GetStream("whoa_mama_Bender", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream futurama_theme_bender
        {
            get
            {
                return ResourceManager.GetStream("futurama_theme_bender", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream you_bastard_bender
        {
            get
            {
                return ResourceManager.GetStream("you_bastard_bender", resourceCulture);
            }
        }







        //Southpark

        internal static System.IO.UnmanagedMemoryStream holy_moly_southpark
        {
            get
            {
                return ResourceManager.GetStream("holy_moly_southpark", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream and_its_gone_Southpark
        {
            get
            {
                return ResourceManager.GetStream("and_its_gone_Southpark", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream yeah_yes_south
        {
            get
            {
                return ResourceManager.GetStream("yeah_yes_south", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream geez_thats_terrible_south_park
        {
            get
            {
                return ResourceManager.GetStream("geez_thats_terrible_south_park", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream intro_Southpark
        {
            get
            {
                return ResourceManager.GetStream("intro_Southpark", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream omg_no_way_Southpark
        {
            get
            {
                return ResourceManager.GetStream("omg_no_way_Southpark", resourceCulture);
            }
        }
        internal static System.IO.UnmanagedMemoryStream nice_Southpark
        {
            get
            {
                return ResourceManager.GetStream("nice_Southpark", resourceCulture);
            }
        }









    }
}
